# Generated by Django 4.0.5 on 2023-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('IIN', models.CharField(max_length=100, unique=True)),
                ('cost', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('profit_earned', models.PositiveIntegerField()),
                ('revenue', models.PositiveIntegerField()),
            ],
        ),
    ]
