# Generated by Django 4.0.5 on 2023-05-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_cancelled',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_recieved',
            field=models.BooleanField(),
        ),
    ]
