# Generated by Django 4.0.5 on 2023-05-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_is_cancelled_alter_orders_is_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_recieved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
